wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.15
    start_time: 1731187118
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 2
      4: 3.10.15
      5: 0.12.21
      8:
      - 5
batch_size:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.0001
num_epochs:
  desc: null
  value: 10
